"""cafe modeliga business_type va feature flags ustunlari qoshish

Revision ID: 4fe5ddf0e8a7
Revises: ca406934e5dd
Create Date: 2026-06-09 00:23:42.274549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe5ddf0e8a7'
down_revision: Union[str, None] = 'ca406934e5dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafes', sa.Column('business_type', sa.String(length=30), nullable=False, server_default='cafe'))
    op.add_column('cafes', sa.Column('enabled_features', sa.JSON(), nullable=True))
    op.add_column('cafes', sa.Column('disabled_features', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cafes', 'disabled_features')
    op.drop_column('cafes', 'enabled_features')
    op.drop_column('cafes', 'business_type')
    # ### end Alembic commands ###
