"""service_cost_room_cost_profit_columns

Revision ID: 56c6f688ae01
Revises: e1f2a3b4c5d6
Create Date: 2026-06-13 10:04:42.606577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56c6f688ae01'
down_revision: Union[str, None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('combo_set_items', 'combo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('combo_set_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_combo_set_items_id'), 'combo_set_items', ['id'], unique=False)
    op.create_index(op.f('ix_combo_sets_id'), 'combo_sets', ['id'], unique=False)
    op.create_index(op.f('ix_daily_specials_id'), 'daily_specials', ['id'], unique=False)
    op.create_index(op.f('ix_daily_specials_tenant_id'), 'daily_specials', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_happy_hours_id'), 'happy_hours', ['id'], unique=False)
    op.create_index(op.f('ix_modifier_groups_id'), 'modifier_groups', ['id'], unique=False)
    op.alter_column('modifiers', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_modifiers_id'), 'modifiers', ['id'], unique=False)
    op.alter_column('order_item_modifiers', 'order_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_item_modifiers', 'modifier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_order_item_modifiers_id'), 'order_item_modifiers', ['id'], unique=False)
    op.alter_column('orders', 'biz_meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('rooms', sa.Column('cost_per_night', sa.Float(), nullable=True))
    op.add_column('services', sa.Column('cost_price', sa.Float(), nullable=True))
    op.add_column('services', sa.Column('commission_pct', sa.Float(), nullable=True))
    op.create_index(op.f('ix_tenant_payments_id'), 'tenant_payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_payments_id'), table_name='tenant_payments')
    op.drop_column('services', 'commission_pct')
    op.drop_column('services', 'cost_price')
    op.drop_column('rooms', 'cost_per_night')
    op.alter_column('orders', 'biz_meta',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_order_item_modifiers_id'), table_name='order_item_modifiers')
    op.alter_column('order_item_modifiers', 'modifier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_item_modifiers', 'order_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_modifiers_id'), table_name='modifiers')
    op.alter_column('modifiers', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_modifier_groups_id'), table_name='modifier_groups')
    op.drop_index(op.f('ix_happy_hours_id'), table_name='happy_hours')
    op.drop_index(op.f('ix_daily_specials_tenant_id'), table_name='daily_specials')
    op.drop_index(op.f('ix_daily_specials_id'), table_name='daily_specials')
    op.drop_index(op.f('ix_combo_sets_id'), table_name='combo_sets')
    op.drop_index(op.f('ix_combo_set_items_id'), table_name='combo_set_items')
    op.alter_column('combo_set_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('combo_set_items', 'combo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
