"""product_sale_unit_qoshish_bosqich_2_3

Revision ID: 7d1f3eff3087
Revises: 6d79dc24c66a
Create Date: 2026-06-09 02:29:53.619229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1f3eff3087'
down_revision: Union[str, None] = '6d79dc24c66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sale_unit', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sale_unit')
    # ### end Alembic commands ###
